In [1]:
import numpy as np

In [3]:
# -----------------------------
# Fuzzy Set Operations
# -----------------------------

def fuzzy_union(A, B):
    return np.maximum(A, B)

def fuzzy_intersection(A, B):
    return np.minimum(A, B)

def fuzzy_complement(A):
    return 1 - A

def fuzzy_difference(A, B):
    return np.maximum(A, 1 - B)

# -----------------------------
# Cartesian Product (Fuzzy Relation)
# -----------------------------

def cartesian_product(A, B):
    return np.minimum.outer(A, B)

In [5]:
# -----------------------------
# Max-Min Composition
# -----------------------------

def max_min_composition(R, S):
    rows_R, cols_R = R.shape
    rows_S, cols_S = S.shape
    
    if cols_R != rows_S:
        raise ValueError("Matrix dimensions do not match for composition")
    
    T = np.zeros((rows_R, cols_S))
    
    for i in range(rows_R):
        for j in range(cols_S):
            T[i][j] = np.max(np.minimum(R[i, :], S[:, j]))
    
    return T

In [7]:
# -----------------------------
# Example Usage
# -----------------------------

# Fuzzy sets
A = np.array([0.2, 0.4, 0.6, 0.8])
B = np.array([0.3, 0.5, 0.7, 0.9])

# Operations
print("Union:", fuzzy_union(A, B))
print("Intersection:", fuzzy_intersection(A, B))
print("Complement of A:", fuzzy_complement(A))
print("Difference (A - B):", fuzzy_difference(A, B))


Union: [0.3 0.5 0.7 0.9]
Intersection: [0.2 0.4 0.6 0.8]
Complement of A: [0.8 0.6 0.4 0.2]
Difference (A - B): [0.7 0.5 0.6 0.8]


In [9]:
# -----------------------------
# Fuzzy Relations
# -----------------------------

# Create relations using Cartesian product
R = cartesian_product(A, B)
S = cartesian_product(B, A)

print("\nRelation R:\n", R)
print("\nRelation S:\n", S)


Relation R:
 [[0.2 0.2 0.2 0.2]
 [0.3 0.4 0.4 0.4]
 [0.3 0.5 0.6 0.6]
 [0.3 0.5 0.7 0.8]]

Relation S:
 [[0.2 0.3 0.3 0.3]
 [0.2 0.4 0.5 0.5]
 [0.2 0.4 0.6 0.7]
 [0.2 0.4 0.6 0.8]]


In [11]:
# Max-Min Composition
composition = max_min_composition(R, S)

print("\nMax-Min Composition (R o S):\n", composition)


Max-Min Composition (R o S):
 [[0.2 0.2 0.2 0.2]
 [0.2 0.4 0.4 0.4]
 [0.2 0.4 0.6 0.6]
 [0.2 0.4 0.6 0.8]]
